window.dataForLabels = {
    sectionInfo: 'Info',
    name: 'Name',
    fullAddress: 'Address',
    phone: 'Phone',
    email: 'E-mail',
    website: 'Website'

};
window.dataForCV = {
    mainPhoto:'https://th.bing.com/th/id/OIP.58kNg_eI3o5Tooupj0_g1AHaDW?w=334&h=158&c=7&o=5&pid=1.7',
    firstName: 'Nikola',
    lastName: 'Gluscevic',
    nameIcon: 'fas fa-user',
    dateOfBirth: 'Date of birth: 22.12.1998.',
    jobTitle: 'Web Developer',
    profile:'Profile',
    adresss:'Adress:',
    imageUrl:'https://www.flaticon.com/svg/static/icons/svg/1051/1051360.svg',
    phoneUrl:'https://www.flaticon.com/svg/static/icons/svg/2947/2947986.svg',
    emailUrl:'https://www.flaticon.com/svg/static/icons/svg/561/561127.svg',
    description:'An articulate professional who can ensure that a business is financially sound, has robust accounting processes, and delivers on its financial targets.<br>Currenty looking for a suitable position with a reputable company.',
    country: 'Country: Montenegro',
    city: 'City: Podgorica',
    street: 'Street: Ul Radula Rusa Radulovica',
    fullAddressIcon: 'fas fa-map-marker',
    contact:'Contact',
    expertise:'Expertise',
    education:'Education',
    html:'HTML',
    empty: 'fill',
    htmlPun: 'fill-percent',
    css:'CSS',
    cssPun:'fill-percent',
    javaS:'Java Script',
    javasPun:'fill-percent2',
    reactJs:'React.js',
    reactJsPun:'fill-percent3',
    language:'English',
    languagePun:'fill-percent4',
    language2:'Germany',
    language2P:'fill-percent5',
    start: '2013-2017',
    school: 'JUSGGŠINŽ."Marko Radevic"',
    start2: '2017-Present',
    school2: 'Civil Engineering',
    phone: '+382/69/603/406',
    phoneIcon: 'fas fa-phone',
    email: 'gluscevicnikola33@gmail.com',
    emailIcon: 'fas fa-envelope',
    website: '',
    websiteIcon: 'fas fa-globe',
    references:'References',
    referencesName:'Avaiable on request.',
    social: {
        facebook: {
            name: 'Facebook',
            icon: 'fab fa-facebook',
            url: 'Facebook.com/nikolagluscevic'
        },
    },
    workexperiance:'Work Experiance',
    start6: '2018-2020',
    company: 'Crnogorski Telekom',
    jobTitle2: 'IT Manager',
    description2: 'Odjeljenje za tehnicku podrsku. Podrske za IP servise i mobilnu telefoniju, komunikaciji sa korisnicima preko Drustvenih mreza i Live chat –a',
    start4: '2020-Present',
    company2: 'Respect Security',
    jobTitle3: 'Web Developer',
    description3: 'Odjeljenje za tehnicku podrsku. Organizacija posla.'
}
